apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    component: frontend
    app: todo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: todo
    component: frontend
